### ISSUE TITLE
Preferred topology field in the input files?

### ISSUE THREAD

**Issue by batukav** [NMRLipids/Databank#10]
As we are planning to do the entire current and future analysis without using the Gromacs tools, I think we should get ready to work without the tpr files.

We can simply use MDAnalysis to perform all the trajectory analysis. MDAnalysis accepts many topology and trajectory formats and capable of aligning the trajectory such that making molecules whole. When the user provides the simulation data, they have multiple options: pdb, tpr, psf, gro, etc... I feel like this could get a bit complicated to handle.

Would it be a good idea to put a "prefered topology" field into the info files, and make this compulsory in all the software dictionaries? Then we can simply pass this argument to the MDAnalysis and proceed with the trajectory analysis.

**Comment by ohsOllila** [comment]
In the case of Gromacs, compulsory files are now trajectory (xtc or trr) and tpr. I think that MDAnalysis reads tpr files, but this is version dependent. For example, it does not yet read Gromacs 2021 tpr files. However, you can always translate tpr+xtc/trr files to, e.g., gro or pdb files which can be then used as an input for MDAnalysis or other package. Therefore, I think that tpr and xtc/trr are enough in the case of Gromacs simulations.

For other programs we should keep the same idea, i.e., the amount of compulsory files is minimal but yet sufficient to make files that enable all the analyses. However, I do not have experience on other softwares so I cannot say which these files would be in practise.

**Comment by pbuslaev** [comment]
Here is a [list](https://docs.mdanalysis.org/2.3.0/documentation_pages/topology/init.html) of topology formats supported by `MDAnalysis`. Probably we can base the choice of topology file formats on that?

**Comment by ohsOllila** [comment]
This is currently implemented for Gromacs and openMM. 

For gromacs, the analysis codes tries to use tpr, but if this does not work due to version dependecies, a gro file is created with Gromacs commands and the created gro is used with MDAnalysis. 

For openMM, a pdb file is given instead of tpr and pdb is used with MDAnalysis. However, this is not yet updated in the [instructions](https://github.com/NMRLipids/Databank/blob/main/Scripts/BuildDatabank/info_files/README.md). 

For example, see are per lipid calculation in [calcALP.py](https://github.com/NMRLipids/Databank/blob/main/Scripts/AnalyzeDatabank/calcAPL.pyl).

I think that similar idea should work also for other programs. However, I am not aware of a code that could be used to check that molecules are whole and that there no inconvenient jumps over pbc in z-direction for other than Gromacs simulations. Therefore, the requirements for other than Gromacs trajectories is more strict currently (this is also not yet in the instructions).

**Comment by ohsOllila** [comment]
This issue overlaps with issue https://github.com/NMRLipids/Databank/issues/5. Therefore, I will close this and we can continue this discussion in https://github.com/NMRLipids/Databank/issues/5.
