### ISSUE TITLE
We cannot match experiments on "total lipid concentration" because this number is useful only for a narrow group of experiments

### ISSUE THREAD

**Issue by comcon1** [NMRLipids/Databank#164]
The total **concentration of lipid components** (`[lipid]= Nlipid*[water]/Nwater, where [water] = 55.5 M`) doesn't make sense as well as the number of water molecules per lipid for some kind of simulations. I suppose one should not match experiments based on comparing this number. 

Number of water mols per lipid makes sense only if all lipids in your mixture have an equal amount of tails. Once you have POPC + TOCL mixture - this number immediately becomes absolutely unusable. However, there is a large amount of people who work only with two-fatty-acid lipids and that number makes sense for them. But we already have CL:PC mixtures merged into the databank (from me and from Milka Doktorova), and I'm going to upload more CL data and also some LipidA data, which has even 6 fatty acids. 

There are two possibilities of how it can be fixed:
- It is much better to compare just the mass percent of water. If you have a lipid with 4 tails, with 6 tails or with 1 tail - the mass of the lipid will always be larger or smaller depending on the type of lipid. So mass water ratio is a number which is more likely to be a parameter of comparison between simulation and experiment. 
- We can measure the number of water molecules per one fatty acid chain. It will also be an OK number which will have sense for all types of lipid and their mixtures. This way is maybe even better than the mass %. 

"total concentration" has an additional disadvantage: it is not a concentration. This equation gives you a concentration only when Nlipid/Nwater is a very-very-very small number. It's OK for liposome experiments. But in the case of solid-state NMR experiments, it is NEVER that. I consider this as some water-per-lipid derivative but becoming much less intuitive than water-per-lipid itself. 

I decided that it would be good to initiate that discussion _before_ we have a lot of data with non-two-fatty-acid lipids...

**Comment by ohsOllila** [comment]
I do not see the problem here. In experiments you should know weights of water and lipids that are put in the system, and based on molecular weights you should be able to calculate the ratio in term of molecules. On the other hand, from simulations it is easy to calculate molecule numbers. If we go for mass percentage here, we need to include molecular weights in the databank. If we go for number of water molecules per one fatty acid chain, we need to define how many chains there are per molecule.

However, if this causes confusion, we should maybe clarify this in the documentation then?

**Comment by comcon1** [comment]
The problem is better seen if you have two experiments with, e.g., TOCL:DOPC. Both have 30 water per lipid. One run is for the mixture 90% CL. Another run is for 10% CL. For the second, the hydration will be close to "full". The first one is dehydrated. 

Also, similar question is, how to measure % of lipid. In CL:PC mixture, 30 mass % of TOCL means that 30% of surface approximately is covered with CL. You can principally compare that bilayer to PG:PC membrane with 30 mass % of PG. If you provide molar % - it is unclear, how the CL:PC membrane looks like, one should recalculate in head to find it out.

**Comment by ohsOllila** [comment]
I still do not see the problem. This value does not say whether it is fully hydrated or not. It is just used to check that hydration level is the same in experiments and simulations. Actual value matters only for low hydration levels. If systems are "fully hydrated", then the value does not have to be exactly the same. There is no area involved in this number.

Or do you mean that we should re-evaluate the value for "fully hydrated" system currently it is like this: "For molar concentrations of water, the exact hydration level is considered only for systems with molar water-to-lipid ratio below 25, otherwise the systems are considered as fully hydrated."?

**Comment by pbuslaev** [comment]
Number of waters per lipid is a typical "hydration" measure in MD simulations that is used routinely across different software. For example, CHARMM-GUI membrane builder uses this measure and it is reported in many simulation papers. I think, that it is better to stick to current definition.

**Comment by comcon1** [comment]
OK. But then indeed, as Samuli mentioned, the definition of "fully hydrated" should be reconsidered. Because 25 water-per-lipid for hexaacyl LipidA and 25 for DMPE are numbers from different universes.

**Comment by ohsOllila** [comment]
Ok, I think that we can solve this when have the first experimental data where this problem occurs. Or do you already have it? This does not affect any additions of simulations.

**Comment by comcon1** [comment]
> Ok, I think that we can solve this when have the first experimental data where this problem occurs. Or do you already have it? This does not affect any additions of simulations.

Yes, as I see there are a lot of issues. So let's close this one until it comes up with a real problem. I am mining that kind of data (with very different lipids) right now. If I succeed with this, I will anyway reopen this question having actual data to refer.
